const PORT = 4040
export const API_URL = `http://localhost:${PORT}`

export const LIMIT = 2

export const PAGINATION_POST_REQUEST = 'PAGINATION_POST_REQUEST'
export const PAGINATION_POST_SUCCESS = 'PAGINATION_POST_SUCCESS'
export const PAGINATION_POST_FAILURE = 'PAGINATION_POST_FAILURE'

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE'
